sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: oyrk5201614
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t7QWdFtqDMwR7BDqcmu
    access-key-secret: ddT4AJAZ95WpEg49bltR94Q5UZUHoO
    bucket-name: gfddg
    ali:
      oss:
        key: LTAI5t7QWdFtqDMwR7BDqcmu
        secret: ddT4AJAZ95WpEg49bltR94Q5UZUHoO
        endpoint: https://gfddg.oss-cn-beijing.aliyuncs.com
        bucket: gfddg
  redis:
    host: localhost
    port: 6379
    password: 5201614
    database: 0
  wechat:
    appid: wx4b41ebf0476c10dd
    secret: 3a36da52251120ea0dc5963cf2b357e5
    mchid : 18169354553
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://58869fb.r2.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess
